version: '3.8'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MYSQL_ROOT_PASSWORD=admin
    command: yarn dev

  mysql:
   environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=metacare
  